### ISSUE TITLE
Missing "lt-parinfer_compiled.js"

### ISSUE THREAD

**Issue by bbbates** [mauricioszabo/lt_parinfer#2]
After I install the plugin, then restart LT, I get the following in the console:

`Error: ENOENT: no such file or directory, open '/Users/me/Library/Application Support/LightTable/plugins/Parinfer/lt-parinfer_compiled.js'`

For LT plugins, the compiled js needs to be committed alongside everything else and available in the release tag, otherwise...."no worky". (That is probably not documented in the plugin developers guide, unfortunately).

Looking forward to testing this out :)

**Comment by mauricioszabo** [comment]
Sorry, it wasn't documented. I made the changes and already sent to then to update the version: https://github.com/LightTable/plugin-metadata/issues/46

I'll keep this open till your problem is solved.

**Comment by mauricioszabo** [comment]
I  think it's solved right now. Can you test it please?

**Comment by bbbates** [comment]
Yep, that fixed it! Looks good, too.
