### ISSUE TITLE
preformatting corrupts file

### ISSUE THREAD

**Issue by danjohansson** [mauricioszabo/lt_parinfer#3]
I tried the parinfer plugin in lighttable and noticed the following two problems when the file is formatted on first edit.

```
(defn test
  ([a1]
  (println "test")
    )
  ([a1 a2]
    (println "test")))
```

becomes

```
(defn test
  ([a1])
  (println "test")

  ([a1 a2
    (println "test")]))
```

and

```
(defn read
  ([a1]
    (first (read a1 1)))
  ([a1 a2]
    (when (> a2 0)
      (try        
        (catch Exception e
          (throw e))))))
```

becomes

```
(defn read
  ([a1
    (first (read a1 1))])
  ([a1 a2
    (when (> a2 0)
      (try        
        (catch Exception e
          (throw e))))]))
```

**Comment by mauricioszabo** [comment]
Yeah, this is a known bug - it's even on the readme.

I'll look at it, the right way would be when opening a file, re-indent it to match parinfer's indentation. For example, your last code:

``` clojure
(defn read
  ([a1]
    (first (read a1 1)))
  ([a1 a2]
    (when (> a2 0)
      (try        
        (catch Exception e
          (throw e))))))
```

would be reindented like this:

``` clojure
(defn read
  ([a1]
   (first (read a1 1)))
  ([a1 a2]
   (when (> a2 0)
     (try        
       (catch Exception e
         (throw e))))))
```

**Comment by danjohansson** [comment]
Ok sorry missed it on the readme.
Thanks for the feedback!

**Comment by mauricioszabo** [comment]
Waiting for metadata update from LightTable, but issue is corrected on master. Will post here when it's published.

**Comment by mauricioszabo** [comment]
Ok, published by https://github.com/LightTable/plugin-metadata/issues/51

Can you confirm the issue is gone?

**Comment by danjohansson** [comment]
Sorry for not confirming sooner.
Opening the file works now but pasting gives the same problem as before.

**Comment by mauricioszabo** [comment]
Same example file? If not, please share the contents you're trying to paste
into the editor.

There had been some huge changes in the master branch, I'll try with the
last tag and master to see if the problem was already solved.

Have you tried to paste in indent mode or paren mode? Disabling (before
paste) and enabling again (after paste) gives the same problems? I know
this is not a valid workaround, but maybe it'll help to diagnose the
problem.

**Comment by shaunlebron** [comment]
I think the last remaining question here is whether we should preprocess pasted code like we do an opened file.  Imagine pasting a whole file into a new one, and you will get the same problem at the beginning of this issue.

**Comment by mauricioszabo** [comment]
Maybe add a "Parinfer - Paste" command that will try to disable parinfer, paste the code, and then re-enable to check if everything is alright?
